baseURL = "https://turva.netlify.com/"
languageCode = "en-us"
theme = "airspace-hugo"
title = "Sec And Safe Oy"
[[menu.footer]]
name = "Terms"
url = "#"
weight = 5
[[menu.footer]]
name = "Blog"
url = "blog"
weight = 4
[[menu.footer]]
name = "How it works"
url = "work"
weight = 3
[[menu.footer]]
name = "Contact us"
url = "contact"
weight = 2
[[menu.footer]]
name = "About us"
url = "#"
weight = 1
[[menu.header]]
name = "Yhteydenotto"
url = "contact"
weight = 3
[[menu.header]]
name = "Palvelumme"
url = "service"
weight = 2
[[menu.header]]
name = "Blogi"
url = "blog"
weight = 1
[params]
home = "Home"
[params.blog]
enable = true
subtitle = "Catch up with us, anytime and anywhere"
title = "Get The Latest On What We're doing"
[params.call]
bgImage = "img/call-to-action-bg.jpg"
enable = true
paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
title = "We design delightful digital experiences."
[params.call.button]
text = "tell us your story"
url = "#"
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "Drop us a note"
[params.contact.box]
address = "North Main Street, Brooklyn Australia"
email = "Email: contact@mail.com"
phone = "Phone: +88 01672 506 744"
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your subject"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.feature]
bgImage = "img/feature-bg.jpg"
content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
enable = true
title = "We believe in great ideas"
[params.feature.button]
caption = "View Works"
url = "#"
[params.slider]
bgImage = "img/slider-bg.jpg"
btnText = "Palveluihimme"
enable = true
subtitle = "Laadukkaat koulutukset vaivattomasti ja kustannustehokkaasti."
title = "Sec And Safe Oy"
url = "http://turva.netlify.com/service"
[params.wrapper]
enable = true
image = "img/wrapper-img.png"
italic = "Arjen turvallisuutta"
paragraph = "Koulutamme useiden eri alojen ammattilaisia, turvallisuuteen liittyen. <br>Olit sitten sosiaali- ja terveydenhoitoalan, kaupan alan tai vaikkapa kuljetusalan ammattilainen. <br>Turvallisuus, ensiapu sekä uhka- ja vaaratilanteiden koulutuksemme auttavat sinua kohtaamaan haastavatkin tilanteet ja selviytymään niistä.<br>\n\nPalveluvalikoimaamme kuuluu myös ammattimaisesti laaditut pelastussuunnitelmat. Sopimuksen mukaan myös ylläpidämme ja päivitämme suunnitelmanne, joten voit jättää huolehtimisen meille.<br>\n\nJärjestämme myös koulutuksia palo- ja pelastusturvallisuuteen, omatoimiseen varautumiseen, sisälle suojautumiseen sekä turvallisuuskävelyiden järjestämiseen liittyen.<br>\n\nTämän lisäksi löydät meiltä myös alkusammutus, työturva sekä tulityökortti koulutukset."
title = "Koulutuspalvelut X on nyt Sec And Safe Oy!"
